# Generated by Django 5.1.1 on 2024-10-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOpeningModel',
            fields=[
                ('count', models.IntegerField(auto_created=True)),
                ('refid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('DOR', models.DateField()),
                ('mobile', models.BigIntegerField()),
            ],
        ),
    ]
